import { FoodItem, emptyNutrients } from '@/types';

// Comprehensive mock fallback (~30 items) for dev/offline/API failure
export const MOCK_FOODS: FoodItem[] = [
  { id: 'mock-1', source: 'mock', label: 'Beef, ground, 85% lean, cooked', brand: null, category: 'Meat',
    nutrientsPer100g: { ...emptyNutrients(), iron: 2.6, protein: 26, iodine: 0.6, selenium: 18, vitaminB12: 2.6, folate: 7, zinc: 5.5, calories: 215, fat: 15 }},
  { id: 'mock-2', source: 'mock', label: 'Spinach, raw', brand: null, category: 'Vegetable',
    nutrientsPer100g: { ...emptyNutrients(), iron: 2.7, protein: 2.9, iodine: 0.3, selenium: 1, folate: 194, vitaminC: 28, zinc: 0.5, fiber: 2.2, calories: 23, carbs: 3.6, fat: 0.4 }},
  { id: 'mock-3', source: 'mock', label: 'Lentils, cooked', brand: null, category: 'Legume',
    nutrientsPer100g: { ...emptyNutrients(), iron: 3.3, protein: 9, selenium: 2.8, folate: 181, vitaminC: 1.5, zinc: 1.3, fiber: 7.9, calories: 116, carbs: 20, fat: 0.4 }},
  { id: 'mock-4', source: 'mock', label: 'Sardines, canned in oil', brand: null, category: 'Fish',
    nutrientsPer100g: { ...emptyNutrients(), iron: 2.9, protein: 25, iodine: 35, selenium: 52.7, vitaminB12: 8.9, folate: 10, zinc: 1.3, calories: 208, fat: 11.5 }},
  { id: 'mock-5', source: 'mock', label: 'Eggs, whole, cooked', brand: null, category: 'Dairy & Eggs',
    nutrientsPer100g: { ...emptyNutrients(), iron: 1.8, protein: 13, iodine: 24, selenium: 30.8, vitaminB12: 1.1, folate: 44, zinc: 1.3, calories: 155, carbs: 1.1, fat: 11 }},
  { id: 'mock-6', source: 'mock', label: 'Chicken breast, cooked', brand: null, category: 'Meat',
    nutrientsPer100g: { ...emptyNutrients(), iron: 1.0, protein: 31, iodine: 1.4, selenium: 27.6, vitaminB12: 0.3, folate: 4, zinc: 1, calories: 165, fat: 3.6 }},
  { id: 'mock-7', source: 'mock', label: 'Salmon, Atlantic, cooked', brand: null, category: 'Fish',
    nutrientsPer100g: { ...emptyNutrients(), iron: 0.8, protein: 25, iodine: 14, selenium: 41.4, vitaminB12: 3.2, folate: 26, zinc: 0.6, calories: 208, fat: 13 }},
  { id: 'mock-8', source: 'mock', label: 'Brown rice, cooked', brand: null, category: 'Grain',
    nutrientsPer100g: { ...emptyNutrients(), iron: 0.5, protein: 2.6, selenium: 9.8, folate: 4, zinc: 0.6, fiber: 1.8, calories: 123, carbs: 26, fat: 0.9 }},
  { id: 'mock-9', source: 'mock', label: 'Orange, raw', brand: null, category: 'Fruit',
    nutrientsPer100g: { ...emptyNutrients(), iron: 0.1, protein: 0.9, selenium: 0.5, folate: 30, vitaminC: 53, zinc: 0.1, fiber: 2.4, calories: 47, carbs: 12, fat: 0.1 }},
  { id: 'mock-10', source: 'mock', label: 'Greek yogurt, plain', brand: null, category: 'Dairy & Eggs',
    nutrientsPer100g: { ...emptyNutrients(), protein: 10, iodine: 35, selenium: 9.7, vitaminB12: 0.7, folate: 7, zinc: 0.5, calories: 59, carbs: 3.6, fat: 0.7 }},
  { id: 'mock-11', source: 'mock', label: 'Broccoli, cooked', brand: null, category: 'Vegetable',
    nutrientsPer100g: { ...emptyNutrients(), iron: 0.7, protein: 2.8, selenium: 2.5, folate: 108, vitaminC: 65, zinc: 0.4, fiber: 3.3, calories: 35, carbs: 7, fat: 0.4 }},
  { id: 'mock-12', source: 'mock', label: 'Sweet potato, cooked', brand: null, category: 'Vegetable',
    nutrientsPer100g: { ...emptyNutrients(), iron: 0.7, protein: 2, folate: 6, vitaminC: 19.6, zinc: 0.3, fiber: 3, calories: 90, carbs: 21, fat: 0.1 }},
  { id: 'mock-13', source: 'mock', label: 'Tofu, firm', brand: null, category: 'Legume',
    nutrientsPer100g: { ...emptyNutrients(), iron: 5.4, protein: 8, selenium: 8.9, folate: 15, zinc: 0.8, fiber: 0.3, calories: 76, carbs: 1.9, fat: 4.8 }},
  { id: 'mock-14', source: 'mock', label: 'Banana, raw', brand: null, category: 'Fruit',
    nutrientsPer100g: { ...emptyNutrients(), iron: 0.3, protein: 1.1, selenium: 1, folate: 20, vitaminC: 8.7, zinc: 0.2, fiber: 2.6, calories: 89, carbs: 23, fat: 0.3 }},
  { id: 'mock-15', source: 'mock', label: 'Almonds, raw', brand: null, category: 'Nut',
    nutrientsPer100g: { ...emptyNutrients(), iron: 3.7, protein: 21, selenium: 4.1, folate: 44, zinc: 3.1, fiber: 12.5, calories: 579, carbs: 22, fat: 50 }},
  { id: 'mock-16', source: 'mock', label: 'Milk, whole', brand: null, category: 'Dairy & Eggs',
    nutrientsPer100g: { ...emptyNutrients(), protein: 3.3, iodine: 20, selenium: 2, vitaminB12: 0.4, folate: 5, zinc: 0.4, calories: 61, carbs: 4.8, fat: 3.3 }},
  { id: 'mock-17', source: 'mock', label: 'Quinoa, cooked', brand: null, category: 'Grain',
    nutrientsPer100g: { ...emptyNutrients(), iron: 1.5, protein: 4.4, selenium: 2.8, folate: 42, zinc: 1.1, fiber: 2.8, calories: 120, carbs: 21, fat: 1.9 }},
  { id: 'mock-18', source: 'mock', label: 'Avocado, raw', brand: null, category: 'Fruit',
    nutrientsPer100g: { ...emptyNutrients(), iron: 0.6, protein: 2, folate: 81, vitaminC: 10, zinc: 0.6, fiber: 6.7, calories: 160, carbs: 9, fat: 15 }},
  { id: 'mock-19', source: 'mock', label: 'Shrimp, cooked', brand: null, category: 'Fish',
    nutrientsPer100g: { ...emptyNutrients(), iron: 2.4, protein: 24, iodine: 35, selenium: 38, vitaminB12: 1.1, folate: 3, zinc: 1.6, calories: 99, carbs: 0.2, fat: 0.3 }},
  { id: 'mock-20', source: 'mock', label: 'Kale, raw', brand: null, category: 'Vegetable',
    nutrientsPer100g: { ...emptyNutrients(), iron: 1.5, protein: 4.3, selenium: 0.9, folate: 141, vitaminC: 120, zinc: 0.6, fiber: 3.6, calories: 49, carbs: 9, fat: 0.9 }},
  { id: 'mock-21', source: 'mock', label: 'Tuna, canned in water', brand: null, category: 'Fish',
    nutrientsPer100g: { ...emptyNutrients(), iron: 1.3, protein: 26, iodine: 17, selenium: 90.6, vitaminB12: 2.1, folate: 4, zinc: 0.8, calories: 116, fat: 0.8 }},
  { id: 'mock-22', source: 'mock', label: 'Chickpeas, cooked', brand: null, category: 'Legume',
    nutrientsPer100g: { ...emptyNutrients(), iron: 2.9, protein: 8.9, selenium: 3.7, folate: 172, vitaminC: 1.3, zinc: 1.5, fiber: 7.6, calories: 164, carbs: 27, fat: 2.6 }},
  { id: 'mock-23', source: 'mock', label: 'Lamb, leg, cooked', brand: null, category: 'Meat',
    nutrientsPer100g: { ...emptyNutrients(), iron: 2.1, protein: 26, selenium: 26.4, vitaminB12: 2.6, folate: 19, zinc: 4.5, calories: 217, fat: 12 }},
  { id: 'mock-24', source: 'mock', label: 'Oats, cooked', brand: null, category: 'Grain',
    nutrientsPer100g: { ...emptyNutrients(), iron: 1.4, protein: 2.4, selenium: 5.3, folate: 6, zinc: 0.6, fiber: 1.7, calories: 71, carbs: 12, fat: 1.5 }},
  { id: 'mock-25', source: 'mock', label: 'Bell pepper, red, raw', brand: null, category: 'Vegetable',
    nutrientsPer100g: { ...emptyNutrients(), iron: 0.4, protein: 1, folate: 46, vitaminC: 128, zinc: 0.3, fiber: 2.1, calories: 31, carbs: 6, fat: 0.3 }},
  { id: 'mock-26', source: 'mock', label: 'Cheese, cheddar', brand: null, category: 'Dairy & Eggs',
    nutrientsPer100g: { ...emptyNutrients(), iron: 0.7, protein: 25, iodine: 39, selenium: 13.9, vitaminB12: 0.8, folate: 18, zinc: 3.1, calories: 403, carbs: 1.3, fat: 33 }},
  { id: 'mock-27', source: 'mock', label: 'Potato, baked, with skin', brand: null, category: 'Vegetable',
    nutrientsPer100g: { ...emptyNutrients(), iron: 1.1, protein: 2.5, selenium: 0.4, folate: 28, vitaminC: 9.6, zinc: 0.3, fiber: 2.2, calories: 93, carbs: 21, fat: 0.1 }},
  { id: 'mock-28', source: 'mock', label: 'Liver, beef, cooked', brand: null, category: 'Meat',
    nutrientsPer100g: { ...emptyNutrients(), iron: 6.5, protein: 26, selenium: 39.7, vitaminB12: 70.6, folate: 260, vitaminC: 1.3, zinc: 5.3, calories: 175, carbs: 3.9, fat: 4.7 }},
  { id: 'mock-29', source: 'mock', label: 'Bread, whole wheat', brand: null, category: 'Grain',
    nutrientsPer100g: { ...emptyNutrients(), iron: 2.5, protein: 13, selenium: 40.3, folate: 42, zinc: 1.8, fiber: 6.8, calories: 247, carbs: 41, fat: 3.4 }},
  { id: 'mock-30', source: 'mock', label: 'Tomato, raw', brand: null, category: 'Vegetable',
    nutrientsPer100g: { ...emptyNutrients(), iron: 0.3, protein: 0.9, selenium: 0.1, folate: 15, vitaminC: 14, zinc: 0.2, fiber: 1.2, calories: 18, carbs: 3.9, fat: 0.2 }},
];

export function searchMock(query: string): FoodItem[] {
  const q = query.toLowerCase();
  return MOCK_FOODS.filter(f =>
    f.label.toLowerCase().includes(q) || f.category.toLowerCase().includes(q)
  );
}
